name: fractal_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=h85f69ea_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cfitsio=3.470=h2bbff1b_7
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.3=h885b0b7_4
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.13.3=h0620614_0
  - freexl=2.0.0=h8276f4a_0
  - geos=3.10.6=he74ecf9_0
  - geotiff=1.7.0=hbf7d8e7_4
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - jpeg=9f=ha349fce_0
  - kealib=1.5.0=h6c4040a_2
  - kiwisolver=1.4.9=py311h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.3=hcdb6601_0
  - libarchive=3.7.7=h88ece9c_0
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=4_hf2e6a31_mkl
  - libboost=1.88.0=h3d2b97d_0
  - libcblas=3.11.0=4_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_0
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=hdf1f3d4_10
  - libglib=2.84.2=h405b238_0
  - libheif=1.18.2=gpl_hc631cee_100
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkml=1.3.0=h68a222c_1022
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.11.0=4_hf9ab0e9_mkl
  - libnetcdf=4.9.3=h0c3980a_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.53=h7351971_0
  - libpq=17.6=h652a1e2_0
  - libspatialite=5.1.0=h6715bb4_2
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzip=1.8.0=h289538f_1
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.7=h4fa8253_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - matplotlib=3.10.7=py311haa95532_0
  - matplotlib-base=3.10.7=py311h26e45b9_0
  - minizip=4.0.6=hb638d1e_0
  - mkl=2025.3.0=hac47afa_454
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - numpy=2.3.5=py311h80b3fa1_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=py311haa95532_1
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.1.0=py311hea0d53e_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - poppler=24.09.0=h10b5248_4
  - poppler-data=0.4.12=haa95532_0
  - proj=9.3.1=h4c8f42b_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=6.9.1=py311h12ec796_0
  - pyqt6-sip=13.10.2=py311h630b2a1_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python_abi=3.11=2_cp311
  - qhull=2020.2=h59b6b97_2
  - qtbase=6.9.2=h916ffc4_3
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - rasterio=1.4.3=py311he5c4563_0
  - rav1e=0.7.1=ha073cba_3
  - setuptools=80.9.0=py311haa95532_0
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=py311haa95532_0
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - tiledb=2.3.3=hd8964de_3
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - uriparser=0.9.8=h5a68840_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - x265=3.5=h2d74725_3
  - xerces-c=3.2.5=he0c23c2_2
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\kvnjn\miniconda3\envs\fractal_env
